### ISSUE TITLE
Long treated as Integer?

### ISSUE THREAD

**Issue by clemi2408** [victools/jsonschema-generator#105]
https://github.com/victools/jsonschema-generator/blob/01060f7f3e352da183ba7ba0e5a52bf9aec53610/jsonschema-generator/src/test/java/com/github/victools/jsonschema/generator/SchemaGeneratorSimpleTypesTest.java#L49

Hey Guys can you explain why long values are integers in the schema?
LG
Clem

**Comment by CarstenWickner** [comment]
Hi Clem,

That's because "integer" means there is no decimal point. And JSON Schema does not differentiate between `short`/`integer`/`long`.
Due to this discrepancy, OpenAPI is adding a `"format": "int32"` for `integer` and `"format": "int64"` for `long`; but in both cases it is `"type": "integer"`.

If you prefer something else, you only need to configure your own Custom Definition for the `long` type.

**Comment by clemi2408** [comment]
Thanks for your fast response and the detailed explanation. 
Is there a way to get int32 and int64 into my schema? Is it doable with an annotation? 
Regards and thanks
Clem

**Comment by CarstenWickner** [comment]
I'm actually planning on adding a standard option for those extra OpenAPI formats in the scope of GH-76, but didn't get to it yet.

I believe an `InstanceAttributeOverride` would be your best choice for that at the moment but I haven't tested it yet.
If I remember correctly, a `StringFormatResolver` (which normally populates the `format` keyword) would be skipped for subschemas with `"type": "integer"`, since that is being misused for non-`string` values in OpenAPI.
