### ISSUE TITLE
Conditional schema generation. 

### ISSUE THREAD

**Issue by javatype** [victools/jsonschema-generator#109]
Hello, 

Could you please let me know as how we can generate the conditional schema as mentioned in here - https://json-schema.org/understanding-json-schema/reference/conditionals.html

I need something like below with which I can validate with only given schema type. 
```json
 "allOf": [
    {
      "if": {
        "properties": {
          "type": {
            "const": "scheme2"
          }
        }
      },
      "then": {
        "$ref": "#/definitions/scheme2"
      }
    },
    {
      "if": {
        "properties": {
          "type": {
            "const": "scheme1"
          }
        }
      },
      "then": {
        "$ref": "#/definitions/scheme1"
      }
    }
  ]
```

**Comment by tukaram57** [comment]
version I am using - 4.9.0

**Comment by CarstenWickner** [comment]
Hi @tukaram57,

Since the schema is generated from code, it‘d be good to see the classes you want to represent.
I can surely tell you how to build that schema then.

If you’re not dead-set on the `if`/`then` keyword but would accept a different (although equivalent) output schema, the solution may be a bit easier.

**Comment by tukaram57** [comment]
@CarstenWickner , Thanks a lot for your response.  

here are my classes(using lombok here) - 

`@Data
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME)
@JsonSubTypes({
        @JsonSubTypes.Type(value = B.class, name = "Child"),
        @JsonSubTypes.Type(value = D.class, name = "abstractchild"),
        @JsonSubTypes.Type(value = D1.class, name = "abstractchild1")
})
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public abstract class A {
    @JsonProperty(required = true)
    String z;
    private String zz;
}


@Data
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class B extends D {
    private String y;
} 
@Data
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME)
@JsonInclude(JsonInclude.Include.NON_EMPTY)
@JsonSubTypes({
        @JsonSubTypes.Type(value = B.class, name = "Child1"),
        @JsonSubTypes.Type(value = B1.class, name = "Child2")
})
public abstract class D extends  A {
    private String x;
    private C c;
}
@Data
public class B1 extends A {
    private String y;
}
@Data
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class C {
    @JsonProperty(required = true)
    private String r;
}` 

Schema(for class A here) I want should have allOf tag like this - 

`  "allOf": [
    {
      "if": {
        "properties": {
          "@type": {
            "const": "Child1"
          }
        }
      },
      "then": {
        "$ref": "#/definitions/B"
      }
    },
    {
      "if": {
        "properties": {
          "@type": {
            "const": "Child2"
          }
        }
      },
      "then": {
        "$ref": "#/definitions/B1"
      }
    }
  ]`

**Comment by CarstenWickner** [comment]
If you include the `jsonschema-module-jackson`, via `configBuilder.with(new JacksonModule()` you get something like this out of the box:

```json
{
  "$schema" : "http://json-schema.org/draft-07/schema#",
  "definitions" : {
    "B-2" : {
      "allOf" : [ {
        "type" : "object",
        "properties" : {
          "z" : {
            "type" : "string"
          }
        }
      }, {
        "type" : "object",
        "properties" : {
          "@type" : {
            "const" : "B"
          }
        }
      } ]
    },
    "B1-2" : {
      "allOf" : [ {
        "type" : "object",
        "properties" : {
          "z" : {
            "type" : "string"
          }
        }
      }, {
        "type" : "object",
        "properties" : {
          "@type" : {
            "const" : "B1"
          }
        }
      } ]
    }
  },
  "anyOf" : [ {
    "$ref" : "#/definitions/B-2"
  }, {
    "$ref" : "#/definitions/B-2"
  }, {
    "$ref" : "#/definitions/B1-2"
  }, {
    "$ref" : "#/definitions/B1-2"
  } ]
}
```

As you can see there are some challenges here:
- I did not expect to encounter abstract types as well as their subtypes in `@JsonSubTypes` which leads to the double-up of the `B` and `B1` references.
- A follow-up issue seems to be that the references get the unnecessary `-2` suffix.
- The values of the `@type` properties are looked-up from the `@JsonTypeName` annotations on the subtypes, but you didn't include those, which leads to the fall-back on the class name. According to my tests that is also how Jackson behaves. Picking it up from within the `@JsonSubTypes` is tricky and in your case with `B` and `B1` being mentioned twice might actually be ambiguous if the `name` values on the `A` class differ from the ones on the `D` class.
- By design, I'm avoiding the `if`/`then`/`else` keywords and using `anyOf` instead. I oriented myself on [this excellent StackOverflow answer](https://stackoverflow.com/a/38781027/5127499) and the following comment from Jason Desrosiers below:
    > I'm not a fan of the `if-then-else` keywords and I refuse to use them. But, if you choose to use it, I suggest always wrapping them in an `allOf` that contains only those three keywords. `{ ...other_keywords..., "allOf": [{ "if": ..., "then": ..., "else": ... }], ...more_keywords... }`
You do follow that suggestion in your desired output, but I followed his refusal to use them as `anyOf` is actually easier to handle.
- And yes, there seems to be some further clean-up potential in regards to the `allOf` adding the `@type` property. I may look into that in the future.
- Similarly, the `anyOf` with multiple equivalent references could be cleaned-up automatically. Another task for another day. ;)

**Comment by beingghuman** [comment]
Hi, Thanks for your time in this. 

- I am right now using `configBuilder.forTypesInGeneral().withSubtypeResolver` and getting `anyOf` tag. Issue is that with this tag, I am not sure as I will validate B or B1(these names are just example and can be replaced with good class names). I am happy with current schema I can generate except this `allOf` requirement. 

- I am using networknt for validation purpose and with manual `allOf` change in schema(looking to automate that), its working great for me.  
Can I take abstract of your reply as "That kind of `allOf` is not possible right now"?

- we can have same value for @type as that of class name (B1, B) instead of Child1/Child2. 

- `JacksonModule` build is adding unwanted '-2'.

**Comment by CarstenWickner** [comment]
1. The `JacksonModule` is internally using the same `SubtypeResolver`. But could potentially be changed to also support `if`/`then` – I get the added readability and the possibly more helpful validation error message.
2. It is possible, but would probably be very close to "manual" through a `TypeAttributeOverride` or `CustomDefinition` (i.e. what the `-generator` and `JacksonModule` do internally). In order for the `if`/`then` to make sense, you need a discriminating/identifying property and the `SubtypeResolver` does not force you to indicate one.
3. Either you accept the `@type` being the class name or you add `@JsonTypeName` annotations to avoid the ambiguity.
4. The `-2` comes from the fact that the `@JsonSubTypes` annotation includes duplicates in your example (through the intermediate `D` type). I don't have a clear idea yet how to fix that. It's kind of an edge case.

**Comment by javatype** [comment]
Thanks again, I am going to add custom Jsonnode manually in generated schema. Easy way out it seems.
