### ISSUE TITLE
Missing method in MemberScope.java

### ISSUE THREAD

**Issue by Agh42** [victools/jsonschema-generator#141]
I'm getting an exception trying to generate a JSON schema with v4.15.1:

`Exception in thread "main" java.lang.NoSuchMethodError: 'java.lang.annotation.Annotation com.github.victools.jsonschema.generator.MemberScope.getContainerItemAnnotationConsideringFieldAndGetterIfSupported(java.lang.Class)'
        at com.github.victools.jsonschema.module.javax.validation.JavaxValidationModule.getAnnotationFromFieldOrGetter(JavaxValidationModule.java:147)
        at com.github.victools.jsonschema.module.javax.validation.JavaxValidationModule.isNullable(JavaxValidationModule.java:189)
        at com.github.victools.jsonschema.module.javax.validation.JavaxValidationModule.isRequired(JavaxValidationModule.java:210)
        at com.github.victools.jsonschema.generator.SchemaGeneratorConfigPart.lambda$isRequired$1(SchemaGeneratorConfigPart.java:150)
`

It seems that MemberScope.getContainerItemAnnotationConsideringFieldAndGetterIfSupported(annotationClass) is missing.

**Comment by Agh42** [comment]
My bad - I had a mismatch in versions between dependencies to jsonschema-module-javax-validation!
Sorry for the noise!

**Comment by jochenberger** [comment]
This was caused by an incompatible change in #139. `com.github.victools:jsonschema-generator:4.14.0` is no longer compatible with `com.github.victools:jsonschema-module-jackson:[4.10.0,5.0.0)`.
cc @CarstenWickner

**Comment by CarstenWickner** [comment]
As stated in the README:
> Since version `4.7`, the release versions of the main generator library and the (standard) victools modules listed above are aligned. It is recommended to use identical versions for all of them to ensure compatibility.

In `4.15` a new method was introduced in the main generator library and is being used by the Jackson module of the same version.

If you use a fixed version for one artefact, the same version should be applied to the other artefacts.

**Comment by jochenberger** [comment]
Since it's apparently *required* instead of merely *recommended* to use the same version, I suggest you change the documentation to reflect that.

**Comment by CarstenWickner** [comment]
Fair enough. Will adjust it to state more clearly that the compatibility between different (minor) versions is not guaranteed. Hence the recommendation (but not necessarily requirement) to always use matching versions.

Just to be sure we are on the same page:
- It is generally possible to use an older module with a new main generator version (since that is always backward-compatible also for modules written by someone else but me).
- Some newer module versions are compatible to older main generator versions.
- If a new module version is making use of new main generator features, the main generator version has to be matching or newer than the module version.
