### ISSUE TITLE
How to implement readOnly attribute?

### ISSUE THREAD

**Issue by CathKilroy** [victools/jsonschema-generator#150]
Hi

I cannot find any way to add the readOnly attribute. Is it implemented yet? If yes, where should i look? If not, can I then implement it with ex. a custom provider?

Br
Casper

**Comment by CarstenWickner** [comment]
Hi Casper,

It's currently not supported as a standard attribute (since it's rather new).
Depending on how you detect whether property is `readOnly` or not, you can use a combination of the following configuration options without having to resort to a full `CustomDefinitionProvider`:
- `SchemaGeneratorConfigBuilder.forFields().withInstanceAttributeOverride()`
- `SchemaGeneratorConfigBuilder.forMethods().withInstanceAttributeOverride()`

A simple example for an `InstanceAttributeOverride` would be:
```java
(schema, member, context) -> {
    if (member.getAnnotationConsideringFieldAndGetter(ReadOnly.class) != null) {
        schema.put("readOnly", true);
    }
}
```

**Comment by CathKilroy** [comment]
Hi Carsten

Thank you again, for the quick response. It solved my problem. I am very impresed of the flexibility of this tool. You just have to know, where to look.

Br
Casper
