### ISSUE TITLE
Resolving a custom annotation for a generic schema

### ISSUE THREAD

**Issue by muliyul** [victools/jsonschema-generator#181]
Trying to implement a generic `oneOf`... How do I get the field's annotation (generically, not hard coded?)

```kotlin
.withCustomDefinitionProvider { type, ctx ->
	val desc = ctx.typeContext.getSimpleTypeDescription(type)
	if(!type.erasedType.isEnum) return@withCustomDefinitionProvider null
        // if field contains annotation then do stuff
}

annotation class TagModifier(val value: SchemaKeyword)

class MyForm(
       @field:TagModifier(SchemaKeyword.TAG_ONEOF)
       val state: State // for example one of: [AZ, AK, WY] etc...
)
```

**Comment by CarstenWickner** [comment]
Hi @muliyul,
Could you elaborate a bit?
What exactly are you asking?
- How to get a field's annotation?
- How to implement a `oneOf`?
- How to add a custom definition for a single field instead of a type as a whole?
- Do you want to indicate a list of values (e.g. `enum` values) or a list of alternative schemas?

**Comment by muliyul** [comment]
> Hi @muliyul,
> Could you elaborate a bit?
> What exactly are you asking?
> 
> * How to get a field's annotation?
> * How to implement a `oneOf`?
> * How to add a custom definition for a single field instead of a type as a whole?
> * Do you want to indicate a list of values (e.g. `enum` values) or a list of alternative schemas?

1. How do I get the reference to the field?
2. I saw other examples here how to implement `oneOf` and others, so I'm not asking the same.
3. Again not exactly what I'm asking but can be helpful.
4. Just a list of values.

**Comment by CarstenWickner** [comment]
Hi @muliyul,

> 1. How do I get the reference to the field?

Short answer: inside a per-type `CustomDefinitionProvider`, you don't. At that point, it's already too late.

> How to add a custom definition for a single field instead of a type as a whole?
> 3. Again not exactly what I'm asking but can be helpful.

You can use a `CustomPropertyDefinitionProvider` instead as described here:
- https://victools.github.io/jsonschema-generator/#custom-property-definitions

----

> Do you want to indicate a list of values (e.g. enum values) or a list of alternative schemas?
> 4. Just a list of values.

This is where I believe you're looking at the wrong keyword. `oneOf` allows you to specify distinct (complex) schemas.
What you're after sounds more like a job for the `enum` keyword.

First of all, I've tried addressing the topic of enums here:
- https://victools.github.io/jsonschema-generator/#what-about-enums

If your use-case is not a "real" enum construct, but just a "normal" field where you want to indicate allowed values for, then I encourage you to have a look at the `configBuilder.forFields().withEnumResolver()` (or its equivalent on a per-type or per-method basis.
- https://victools.github.io/jsonschema-generator/#quot-const-quot-quot-enum-quot-keyword

Please let me know if that helps, if there are any follow-up questions, and/or if there's a way to improve the linked documentation.

**Comment by muliyul** [comment]
Thanks I'm pretty new to JSON schemas so it is quite possible I misunderstood some of its concepts. What I'm interested in building is a complex form model with dependent questions so if you can point me in the right direction that would help.

**Comment by CarstenWickner** [comment]
Hi @muliyul,

My personal use-case for using JSON Schema hasn't yet touched upon the generation of forms from it, which is why I can't really point to anything in that area.
I'd generally suggest making yourself more acquainted with JSON Schema in general. My favorite source for that would be:
- https://json-schema.org/understanding-json-schema/reference/index.html

I'm confident you'll be able to create even complex JSON Schemas with this generator library.
If you have other specific questions in the future, I'm happy to assist again.
