### ISSUE TITLE
Support @JsonProperty annotations on methods

### ISSUE THREAD

**Issue by rfox12** [victools/jsonschema-generator#198]
jsonschema-generator has proven to be an amazing and extensible tool.  I have a large, complicated code base with very specific needs, and through the configuration overrides I have been able to do everything I need so far.  Kudos.  In my 20+ years of dealing with code, it's rare to have a system that is truly extensible.  

My question for this issue is: how can I support interface properties at the root level?  We make heavy use of interfaces (and default properties) in order to not pollute our DTOs, and to provide interface users testable flags / values.  Example here (sorry for all the code but I wanted to include a complete copy/paste example). 
```java
package dev.insightminer.interfacegenerator.test;

import java.io.IOException;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonProperty.Access;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.github.victools.jsonschema.generator.Option;
import com.github.victools.jsonschema.generator.OptionPreset;
import com.github.victools.jsonschema.generator.SchemaGenerator;
import com.github.victools.jsonschema.generator.SchemaGeneratorConfig;
import com.github.victools.jsonschema.generator.SchemaGeneratorConfigBuilder;
import com.github.victools.jsonschema.generator.SchemaVersion;
import com.github.victools.jsonschema.module.jackson.JacksonModule;
import com.github.victools.jsonschema.module.jackson.JacksonOption;

public class ReproducibleExample {
	public static interface MaybeCancellable {
		@JsonProperty(value="cancellable", access = Access.READ_ONLY)
		public default Boolean getCancellable() {
			return null;
		}
	}

	public static interface Cancellable extends MaybeCancellable {
		@Override
		@JsonProperty(value="cancellable", required = true, defaultValue = "true", access = Access.READ_ONLY)
		public default Boolean getCancellable() {
			return true;
		}
	}
	
	public static abstract class Task implements MaybeCancellable {
		public String name;
		public Integer myNumber;
	}
	
	public static final class CancellableConcreteTask extends Task implements Cancellable {
		public String cancelReason;
	}
	
	public static final class OtherConcreteTask extends Task {
		public String otherAttribute;
	}

	
	public static void main(String[] args) throws IOException {
		JacksonModule module = new JacksonModule(JacksonOption.RESPECT_JSONPROPERTY_REQUIRED);
		SchemaGeneratorConfigBuilder configBuilder = new SchemaGeneratorConfigBuilder(SchemaVersion.DRAFT_7, OptionPreset.PLAIN_JSON)
				.with(Option.FORBIDDEN_ADDITIONAL_PROPERTIES_BY_DEFAULT)
				.with(Option.MAP_VALUES_AS_ADDITIONAL_PROPERTIES)
				.with(module)
				;
		SchemaGeneratorConfig config = configBuilder.build();
		SchemaGenerator generator = new SchemaGenerator(config);
		

		ObjectMapper mapper = new ObjectMapper();
		mapper.enable(SerializationFeature.INDENT_OUTPUT);

		CancellableConcreteTask cct = new CancellableConcreteTask();
		System.out.println(mapper.writeValueAsString(cct));

		System.out.println("-------------------------");

		ObjectNode cancellableSchema = generator.generateSchema(CancellableConcreteTask.class);
		System.out.println(mapper.writeValueAsString(cancellableSchema));

		System.out.println("-------------------------");
		
		OtherConcreteTask oct = new OtherConcreteTask();
		System.out.println(mapper.writeValueAsString(oct));

		System.out.println("-------------------------");
		
		ObjectNode notCancellableSchema = generator.generateSchema(OtherConcreteTask.class);
		System.out.println(mapper.writeValueAsString(notCancellableSchema));
	}
}
```
produces this output:
```json
{
  "name" : null,
  "myNumber" : null,
  "cancelReason" : null,
  "cancellable" : true
}
-------------------------
{
  "$schema" : "http://json-schema.org/draft-07/schema#",
  "type" : "object",
  "properties" : {
    "cancelReason" : {
      "type" : "string"
    },
    "myNumber" : {
      "type" : "integer"
    },
    "name" : {
      "type" : "string"
    }
  },
  "additionalProperties" : false
}
-------------------------
{
  "name" : null,
  "myNumber" : null,
  "otherAttribute" : null,
  "cancellable" : null
}
-------------------------
{
  "$schema" : "http://json-schema.org/draft-07/schema#",
  "type" : "object",
  "properties" : {
    "myNumber" : {
      "type" : "integer"
    },
    "name" : {
      "type" : "string"
    },
    "otherAttribute" : {
      "type" : "string"
    }
  },
  "additionalProperties" : false
}
```
So you can see the schemas generated are missing the `cancellable` attribute.

In my case the classes and interfaces are in separate files, I've just included them here for ease of illustration.  I think that matters because this example and the separate file example would be different implementation fixes (?)  

I don't know quite enough about this code base yet to issue a PR (sorry).  But I do have some experience with reflection on interfaces (using classmate).  `ResolvedType` has a `getImplementedInterfaces()` method, and one perhaps useful note is that if you want to get annotation detail on interface default methods you may need to use the `ResolvedTypeWithMembers` class with some special configuration:
```java
AnnotationConfiguration annConfig = new AnnotationConfiguration.StdConfiguration(AnnotationInclusion.INCLUDE_BUT_DONT_INHERIT);
ResolvedTypeWithMembers resolvedTypeWithMembers = memberResolver.resolve(resolvedType, annConfig, null);
```
Any help appreciated.  I'm creating complex schemas with flying colors so far.  Support for interfaces is really the only missing link for me.  Thank you for reading.

**Comment by CarstenWickner** [comment]
Hi @rfox12,

Thanks again for the kind words.
There are multiple points in here that are worth addressing individually.

#### 1. Why are the cancellable methods missing?
You're using the `OptionPreset.PLAIN_JSON`, which does not contain the `Option.NONSTATIC_NONVOID_NONGETTER_METHODS`. But that's what the `getCancellable()` methods are as there is no corresponding field.
An overview of the individual `Option` values and in which standard `OptionPreset` they are contained can be found here: https://victools.github.io/jsonschema-generator/#generator-options
You can create your own `OptionPreset` or simply add that single `Option` on top of the `OptionPreset.PLAIN_JSON`.

In case you don't have a `@JsonProperty(value="cancellable")` on all relevant interface methods, you'll probably also be interested in the `Option.FIELDS_DERIVED_FROM_ARGUMENTFREE_METHODS` then, in order to get the `"cancellable"` property instead of a `"getCancellable()"` property automatically. 😉

#### 2. Does it matter whether the various types in a given type hierarchy are defined in multiple files or one?
Whether or not a given type is a (`static`) part of its super or subtype should be irrelevant. As far as I can tell, classmate doesn't care about that. The only difference would be the name of the nested types in comparison to them being properly separated.
The majority of my tests are using nested types purely for the sake of readability in those tests.

#### 3. How to access the `@JsonProperty` annotation on an overridden interface method?
This is not shown in your reproducible example, as you are missing the `"cancellable"` altogether, but I imagine that to be the next challenge. I haven't yet tested it, but internally the classmate `ResolvedMethod.getAnnotation()` method is being called (in case of the `JacksonModule` you're using):
https://github.com/victools/jsonschema-generator/blob/b6595b9e01623680d0f8bdca8ba4c96a0a670a4b/jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/MemberScope.java#L265

#### 4. How to apply a different AnnotationConfiguration on classmate?
The current default setting is `AnnotationInclusion.INCLUDE_AND_INHERIT_IF_INHERITED`.

That being said, I'm happy to inform you that this is already configurable.
It's just not properly documented as I didn't yet encounter an actual use-case for it. Nevertheless, you can provide an `AnnotationInclusion` of your choosing in one of the offered [`TypeContextFactory`](https://github.com/victools/jsonschema-generator/blob/master/jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/impl/TypeContextFactory.java) methods or you go straight for one of the [`TypeContext`](https://github.com/victools/jsonschema-generator/blob/master/jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/TypeContext.java) constructors.
That `TypeContext` instance can then be provided in the `SchemaGenerator` contructor.

**Comment by rfox12** [comment]
Thank you for the prompt reply!  Indeed NONSTATIC_NONVOID_NONGETTER_METHODS was the option that I needed.  And I appreciate the comment FIELDS_DERIVED_FROM_ARGUMENTFREE_METHODS, however, for my team that is one step into the magic too far, sir.  :)  So I'm trying to augment JacksonModule to deal with methods.  The fix seems fairly straightforward if we're concerned mostly with _required_ and the value name.  This is what I have so far...

```java
public static class JacksonMethodModule implements Module {
  @Override
  public void applyToConfigBuilder(SchemaGeneratorConfigBuilder builder) {
    SchemaGeneratorConfigPart<MethodScope> methodConfigPart = builder.forMethods();
    methodConfigPart.withPropertyNameOverrideResolver(method -> Optional.ofNullable(method.getAnnotation(JsonProperty.class)).map(ann -> ann.value().isBlank() ? null : ann.value().strip()).orElse(null));
    methodConfigPart.withRequiredCheck(method -> Optional.ofNullable(method.getAnnotation(JsonProperty.class)).map(JsonProperty::required).orElse(false) == true);
  }
}
```
Which seems to work well!... except for the fact that the empty parens are still applied, so I end up with `cancellable()` in the output.  I took a peek into the code and it looks like (unfortunately) that getting rid of that would require something more drastic.

`doGetSchemaPropertyName` in [MethodScope](https://github.com/victools/jsonschema-generator/blob/master/jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/MethodScope.java
):
```java
    /**
     * Returns the name to be used to reference this method in its parent's "properties".
     *
     * @return the (potentially overridden) name of the method followed by its argument types in parentheses
     * @see #getName()
     * @see TypeContext#getMethodPropertyArgumentTypeDescription(ResolvedType)
     */
    @Override
    protected String doGetSchemaPropertyName() {
        String result = this.getName();
        if (this.getContext().isDerivingFieldsFromArgumentFreeMethods() && this.getArgumentCount() == 0) {
            if (this.getOverriddenName() == null) {
                // remove the "get"/"is" prefix from non-overridden method names
                if (result.startsWith("get") && result.length() > 3) {
                    result = Character.toLowerCase(result.charAt(3)) + result.substring(4);
                } else if (result.startsWith("is") && result.length() > 2) {
                    result = Character.toLowerCase(result.charAt(2)) + result.substring(3);
                } else {
                    result += "()";
                }
            }
        } else {
            result += this.getArgumentTypes().stream()
                    .map(this.getContext()::getMethodPropertyArgumentTypeDescription)
                    .collect(Collectors.joining(", ", "(", ")"));
        }
        return result;
    }
}
```
So here you can see that if the FIELDS_DERIVED_FROM_ARGUMENTFREE_METHODS is set, you can't override the name, and if it's not set, you are stuck with arguments (or empty parens) being appended.  I was very hopeful that this would be a clean fix.  What do you recommend at this point?

**Comment by CarstenWickner** [comment]
Hi @rfox12,

- The `doGetSchemaPropertyName()` method you copied here shows, that the parentheses are only omitted if the `Option.FIELDS_DERIVED_FROM_ARGUMENTFREE_METHODS` is enabled. That's a must-have for you then. There are no additional methods being included by this. It is merely deciding whether to omit the parentheses or not. 😉
- If you then override the name (e.g. based on the `@JsonProperty(value)`), it should work as you want. Your given configuration looks fine there.
- To avoid the unannotated methods to be included, just add another `IgnoreCheck`, e.g.
```java
    methodConfigPart.withIgnoreCheck(method -> method.getAnnotation(JsonProperty.class) == null);
```

**Comment by rfox12** [comment]
Thank you!  I'll leave this issue to close at your discretion.  Not sure if you wanted to add to `JacksonModule` or not.

**Comment by CarstenWickner** [comment]
Yes, I intend to incorporate this at some point, just need to come up with appropriate names for the `JacksonOption` values for toggling the behavior around methods.
Backward compatibility concerns are the only thing that stopped me from doing it already (that and lack of time 😉).

Since everything is designed to be highly configurable, I guess there's always an easy workaround for something like this. I'll include it nonetheless, just haven't made up my mind whether the default module behavior should change (i.e. always considering methods) or not: so making it an "opt-in" or "opt-out" `JacksonOption`.

**Comment by CarstenWickner** [comment]
After further consideration, I decided to leave out the extra `JacksonOption` for now.
As per comment on PR #206:
> Based on the assumption that the majority of existing use-cases involving the `JacksonModule` either ignore all (non-getter) methods implicitly or explicitly already, there is no need to introduce another `JacksonOption` for turning the new method-related logic off in general.
Such a `JacksonOption` could be easily added (as "opt-out") if someone asks for it.
