### ISSUE TITLE
Missing $ref on CustomPropertyDefinition

### ISSUE THREAD

**Issue by pefernan** [victools/jsonschema-generator#205]
Hello,

I'm working in a project where we do have to generate json schemas for complex objects (with possible cross dependencies between models), so we need to use model references. And we also need to generate som custom metadata if the model fields contain certain annotations, so we are using to do that `CustomPropertyDefinition` to do that. 

We found that when creating a `DefinitionReference` to be used on a  `CustomPropertyDefinition` in the final json schema, the property node misses the `$ref` attribute.

Example of model:

```java
class Address {...}
class Person {
    String name;
    Address address;
    Person parent;
}

class TaskInputModel {
    @UserTaskParam("input")
    Person person;
}
```

Example of code:
```java
SchemaGeneratorConfigBuilder builder = new SchemaGeneratorConfigBuilder(schemaVersion, OptionPreset.PLAIN_JSON);
builder.with(Option.DEFINITIONS_FOR_ALL_OBJECTS);
builder.forFields()
    .withCustomDefinitionProvider((scope, context) -> {
        UserTaskParam param = scope.getAnnotation(UserTaskParam.class);
        if (param != null) {
            ObjectNode objectNode = context.createStandardDefinitionReference(scope.getDeclaredType(), null);
            return new CustomPropertyDefinition(objectNode, AttributeInclusion.YES);
        }
        return null;
    });
```

Result json schema:
```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "Address": {
      "type": "object",
      "properties": {...}
    },
    "Person": {
      "type": "object",
      "properties": {
        "address": {
          "$ref": "#/definitions/Address"
        },
        "name": {
          "type": "string"
        },
        "parent": {
          "$ref": "#/definitions/Person"
        }
      }
    }
  },
  "type": "object",
  "properties": {
    "person": {} // here we are missing the `$ref`
  }
}
```

As a workaround we are adding the `$ref` manually but I think it may be automatically handled.

**Comment by CarstenWickner** [comment]
Hi @pefernan,

I can reproduce the issue and have a few remarks:
1. Since you're targeting "JSON Schema Draft 7", please note that a schema containing `$ref` should contain nothing else. Only from "JSON Schema Draft 2019-09" onward is that officially allowed.
2. Please don't include the output of `context.createStandardDefinitionReference()` directly as the custom definition. This is **always an empty ObjectNode** at that point (i.e. no `$ref` yet).
3. Everything you declare on the root node of the `CustomDefinition` is shallow-copied and the root node itself is subsequently ignored. Unfortunately, that ignored node is later receiving the `$ref` property when the final schema is being built.

The solution/workaround is to heed the advice from the `context.createStandardDefinitionReference()` method's JavaDoc:
> The returned node will be empty, but is being remembered internally and populated later, i.e. it should not be changed!

Instead, wrap the standard definition reference into an `"allOf"` array, and put that into your custom definition:
```java
ObjectNode customDefinitionRoot = context.getGeneratorConfig().createObjectNode();
ArrayNode allOf = customDefinitionRoot.withArray(context.getKeyword(SchemaKeyword.TAG_ALLOF));
allOf.add(context.createStandardDefinitionReference(scope.getDeclaredType(), null));
ObjectNode customPart = allOf.addObject();
// in this "customPart", you can add whatever you need to add
customPart.put("custom", "part");
return new CustomPropertyDefinition(customDefinitionRoot, CustomDefinition.AttributeInclusion.YES);
```
That produces the desired output.
```json
{
  "$schema" : "http://json-schema.org/draft-07/schema#",
  "definitions" : {
    "Address" : { ... },
    "Person" : {
      "type" : "object",
      "properties" : {
        "address" : {
          "$ref" : "#/definitions/Address"
        },
        "name" : {
          "type" : "string"
        },
        "parent" : {
          "$ref" : "#/definitions/Person"
        }
      }
    }
  },
  "type" : "object",
  "properties" : {
    "person" : {
      "allOf" : [ {
        "$ref" : "#/definitions/Person"
      }, {
        "custom" : "part"
      } ]
    }
  }
}
```

Side note: if you switch to target `SchemaVersion.DRAFT_2019_09` at some point in the future, the unnecessary `"allOf"` would be cleaned-up automatically to:
```json
{
  "$defs": { ... },
  "type" : "object",
  "properties" : {
    "person" : {
      "$ref" : "#/$defs/Person",
      "custom" : "part"
    }
  }
}
```

**Comment by pefernan** [comment]
@CarstenWickner thank you for your response!

I wasn't aware I had to keep the node with `$ref` empty and use a `allOf` to join both nodes. I'll give it a try and see if that works on my setup! Also will give a try at "Draft 2019-09" to see if that works too.

Thank you again!
