### ISSUE TITLE
Extract enums to definitions with DEFINITIONS_FOR_ALL_OBJECTS

### ISSUE THREAD

**Issue by ALEUT** [victools/jsonschema-generator#23]
I will suggest extract enums to definitions too if DEFINITIONS_FOR_ALL_OBJECTS is defined because in Java they're also different objects, not primitives.

**Comment by CarstenWickner** [comment]
Hi @ALEUT,
Since enums are special there are actually three ways of handling them:
- `Option.FLATTENED_ENUMS` (which is part of the `OptionPreset.PLAIN_JSON`)
- `Option.SIMPLIFIED_ENUMS`(which is part of the `OptionPreset.JAVA_OBJECT` and `OptionPreset.FULL_DOCUMENTATION`), which makes them eligible to be moved into the `definitions`.
- Or using neither to let them be handled like any other class -- also making them eligible to be moved into the `definitions`.

You can switch between those three alternatives via the `SchemaGeneratorConfigBuilder.with(Option)` and `SchemaGeneratorConfigBuilder.without(Option)` methods.

Do you still see any extra need for handling enums in a different way in case of `Option.FLATTENED_ENUMS`?

**Comment by ALEUT** [comment]
Looks no - it can be closed, thanks!
