### ISSUE TITLE
BOM is not in maven or central repo

### ISSUE THREAD

**Issue by mikezerosix** [victools/jsonschema-generator#241]
I really love that you made a BOM for this lib, but it is not found in any main Maven repos. 
Could you please add it ? 

https://mvnrepository.com/artifact/com.github.victools

**Comment by CarstenWickner** [comment]
Hi @mikezerosix,

You're absolutely right, the BOM wasn't properly being published.
I've now refactored the whole multi-module build to incorporate the BOM instead of just adding it half-heartedly on the side.

I've released it as [v4.24.2](https://github.com/victools/jsonschema-generator/releases/tag/v4.24.2) now – which doesn't contain any functional changes in comparison to v4.24.1. Only the restructured POM hierarchy and the fixed-up BOM artifact.
The BOM was successfully published to https://oss.sonatype.org and should be available on other Maven repositories in due time.
