### ISSUE TITLE
Generation from an annotation processor

### ISSUE THREAD

**Issue by marceloavan** [victools/jsonschema-generator#247]
I have a use case of metadata generation from a self-implemented annotation processor. My idea was to generate the json schema from the same point, but the problem is, you might know, at this point, there is no "Class/Type" available because it is on the build step. There is another group of interfaces (TypeMirror/Element) with a similar level of information, but is not compatible.

So my question is if there is some way to adapt it or maybe another similar project aiming at the annotation processor. Of course, let me know if I'm missing something or looking from the wrong perspective.

**Comment by CarstenWickner** [comment]
Hi @marceloavan,

I don't quite follow. Are you auto-generating classes based on your metadata definitions?
If yes, then you could produce the json schema for those generated classes.
Even if not, you could introduce such a code generation step just for the sake of the json schema and afterwards throw away the unwanted generated classes.

Otherwise, I'm afraid a more generic help site (such as StackOverflow) may give you a higher chance of getting suitable suggestions.

**Comment by marceloavan** [comment]
Hey @CarstenWickner 

Thank you for your reply. Actually, I have some classes being created by the developers on some projects. These projects have the annotation processor (which I mentioned) extracting some metadata from them. So my idea is also to generate the JSON schema from these classes, which are POJOs with some annotations.

My point is that the SchemaGeneratior accepts a "Type" reference, while in the annotation processor I just have "TypeMirror", so it is not possible to use the "conventional" way calling `SchemaGenerator.generateSchema(type)`.

**Comment by CarstenWickner** [comment]
Hi @marceloavan,

Your question sounds like you simply want to determine the underlying `Class` (plus potential argument types) from a given `TypeMirror`.
Since the `TypeMirror` implementations contain the necessary information, you should be able to derive that information regardless of the JSON Schema Generator use-case here.

Therefore my suggestion to look for a generic approach, such as per this question: https://stackoverflow.com/q/19785870/5127499

**Comment by marceloavan** [comment]
Yep, @CarstenWickner, you're totally right.

It is just not that simple to determine the underlying `Class` because the annotation processing lives on the build phase, so the solutions which I've found sound more like "workarounds" than something that I was confident about, that's why I've created this issue.

Also, I've found this implementation doing something similar using the `Class.forName`: https://github.com/versly/wsdoc/blob/master/src/main/java/org/versly/rest/wsdoc/AnnotationProcessor.java#L950, but it didn't work well for me, maybe caused by a side issue.

> Since the TypeMirror implementations contain the necessary information, you should be able to derive that information regardless of the JSON Schema Generator use-case here.

You are also right here, I will probably extract the information from the `TypeMirror` and create the schema file in a self-implementation.

Help a lot @CarstenWickner, thank you for your time.
