### ISSUE TITLE
Issue with Java Map

### ISSUE THREAD

**Issue by patpatpat123** [victools/jsonschema-generator#367]
Hello team,

Hope you are well.
Just wanted to reach out with a small technical issue.

I have a pojo which looks like this:

```java
@JsonClassDescription("MyPojo")
public record MyPojo(
    @JsonPropertyDescription("A map of string -> list of string")
    Map<String, List<String>> aaa;
    @JsonPropertyDescription("A generic map")
    Map<?, ?> bbb;
    @JsonPropertyDescription("Another generic map")
    Map<?, ?>ccc;
}
```

Using the latest version of this project, 

```xml
 <dependency>
            <groupId>com.github.victools</groupId>
            <artifactId>jsonschema-generator</artifactId>
            <version>4.31.1</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.github.victools</groupId>
            <artifactId>jsonschema-module-jackson</artifactId>
            <version>4.31.1</version>
            <scope>test</scope>
        </dependency>
```

And the code as suggested by this repo:

```java
SchemaGenerator generator = new SchemaGenerator(configBuilder.build());
ObjectNode jsonNode = generator.generateSchema(MyPojo.class);
```

I get as result:
```json
{
  "$defs" : {
    "Map(Object,Object)" : {
      "type" : "object"
    }
  },
  "type" : "object",
  "properties" : {
    "aaa" : {
      "type" : "object",
      "description" : "A map of string -> list of string"
    },
    "bbb" : {
      "$ref" : "#/$defs/Map(Object,Object)",
      "description" : "A generic map"
    },
    "ccc" : {
      "$ref" : "#/$defs/Map(Object,Object)",
      "description" : "Another generic map"
    }
  }
}
```

Couple of inputs:

1 - why ```aaa``` is an object, and not a ``` "$ref" : "#/$defs/Map(String,xxx)",``` (I do not know what would be list of string). It looks like some map are treated as map, some as object, is it possible to unify that?

2 Is it possible for ```bbb``` and ```ccc``` to have 
``` 
"type" : "Map(Object,Object)",
``` 
instead of this rather complex  
```"$ref" : "#/$defs/Map(Object,Object)",``` + 
```
 "$defs" : {
          "Map(Object,Object)" : {
            "type" : "object"
          }
        },
```

please?

Thank you for your help

**Comment by CarstenWickner** [comment]
HI @patpatpat123,

1. By default, the `$ref` is only included if a particular type is referenced more than once (like the `Map<?, ?>`). If you also want it for the one-time `Map<String, List<String>`, then you can include this:
```java
    configBuilder.with(Option.DEFINITIONS_FOR_ALL_OBJECTS);
```
2. The `type` keyword is not a free-text field but has a small set of predefined values, that can be used. In the context of a JSON schema, the `type` to represent a Java `Map` would be `"object"`, otherwise it is an invalid JSON schema, i.e., no: you cannot you the `type` keyword for this. But you could use something else, e.g., the `title` as per the examples given in the documentation:
https://victools.github.io/jsonschema-generator/#quot-title-quot-keyword

You might also want to consider the `Option.MAP_VALUES_AS_ADDITIONAL_PROPERTIES` that is listed on row 25 in the documentation of available standard `Option` values as well:
https://victools.github.io/jsonschema-generator/#generator-options

**Comment by patpatpat123** [comment]
Very clear @CarstenWickner , thank you.

May I ask if it is possible to skip the "particular type referenced more than once", i.e, how to achieve this?

```
{
  "type" : "object",
  "properties" : {
    "aaa" : {
      "type" : "object",
      "description" : "A map of string -> list of string"
    },
    "bbb" : {
      "type" : "object",
      "description" : "A generic map"
    },
    "ccc" : {
      "type" : "object",
      "description" : "Another generic map"
    }
  }
}
```

**Comment by CarstenWickner** [comment]
You can use `Option.INLINE_ALL_SCHEMAS` (row 31 in the documentation).

You need to be careful with this `Option` though. Complex/recursive data structures may contain self-references, leading to an endless loop, i.e., the schema cannot be generated then.
This option would be the way to go however for such a simple example.

**Comment by patpatpat123** [comment]
Exactly what I was looking for. Many thanks @CarstenWickner
