### ISSUE TITLE
MAP_VALUES_AS_ADDITIONAL_PROPERTIES and DEFINITIONS_FOR_ALL_OBJECTS duplicates additional properties

### ISSUE THREAD

**Issue by magicDGS** [victools/jsonschema-generator#420]
Given the following model(s):

```java
@JsonPropertyOrder({"string_value", "int_value"})
public static class ValueSchema {
    @JsonProperty("int_value")
    public Integer intValue;
    @JsonProperty("string_value")
    public String stringValue;
}

public static class MapSchema {
    @JsonProperty("map_value")
    public Map<String, ValueSchema> mapValue;
}
```

Using the following generator:

```java
new SchemaGenerator(
    new SchemaGeneratorConfigBuilder(SchemaVersion.DRAFT_2019_09, OptionPreset.PLAIN_JSON)
            .with(new JacksonModule())
            .with(Option.MAP_VALUES_AS_ADDITIONAL_PROPERTIES)
            .with(Option.DEFINITIONS_FOR_ALL_OBJECTS)
            .build());
````

I expect a schema as following:

```json
{
  "$schema" : "https://json-schema.org/draft/2019-09/schema",
  "$defs" : {
    "Map(String,ValueSchema)" : {
      "type" : "object",
      "additionalProperties" : {
        "$ref" : "#/$defs/ValueSchema"
      }
    },
    "ValueSchema" : {
      "type" : "object",
      "properties" : {
        "int_value" : {
          "type" : "integer"
        },
        "string_value" : {
          "type" : "string"
        }
      }
    }
  },
  "type" : "object",
  "properties" : {
    "map_value" : {
      "$ref" : "#/$defs/Map(String,ValueSchema)"
    }
  }
}
```

Nevertheless, I found the following schema:

```json
{
  "$schema" : "https://json-schema.org/draft/2019-09/schema",
  "$defs" : {
    "Map(String,ValueSchema)" : {
      "type" : "object",
      "additionalProperties" : {
        "$ref" : "#/$defs/ValueSchema"
      }
    },
    "ValueSchema" : {
      "type" : "object",
      "properties" : {
        "int_value" : {
          "type" : "integer"
        },
        "string_value" : {
          "type" : "string"
        }
      }
    }
  },
  "type" : "object",
  "properties" : {
    "map_value" : {
      "$ref" : "#/$defs/Map(String,ValueSchema)",
      "additionalProperties" : {
        "$ref" : "#/$defs/ValueSchema"
      }
    }
  }
}
```

Note that it contains the `additionalProperties` twice: one on the `$defs` that is referenced by `map_value` and also on the `map_value` itself.

**Comment by CarstenWickner** [comment]
Hi @magicDGS,

That is somewhat on purpose.
In the context of a field/method, there may be additional attributes being collected that narrow the scope somewhat.
E.g. for a type like this:
```java
class TestType {
    public Map<String, @Size(min = 3, max = 50) String> oneMap;
    public Map<String, String> otherMap;
}
```
The produced schema (with `Option.DEFINITIONS_FOR_ALL_OBJECTS`) is the following:
```json
{
  "$schema" : "https://json-schema.org/draft/2020-12/schema",
  "$defs" : {
    "Map(String,String)" : {
      "type" : "object",
      "additionalProperties" : {
        "type" : "string"
      }
    }
  },
  "type" : "object",
  "properties" : {
    "oneMap" : {
      "$ref" : "#/$defs/Map(String,String)",
      "additionalProperties" : {
        "type" : "string",
        "minLength" : 3,
        "maxLength" : 50
      }
    },
    "otherMap" : {
      "$ref" : "#/$defs/Map(String,String)",
      "additionalProperties" : {
        "type" : "string"
      }
    }
  }
}
```
The type `Map<String, String>` is unaware of the additional attributes associated with the one particular occurrence.
I suppose, the field attribute should be omitted if it matches the general type attribute. Also because the meaning of `additionalProperties` are different in combination with a `$ref` vs. specific `properties`. Fortunately in this case: there are no other `properties`, i.e., the schema is still valid even with the `additionalProperties` in two places.

The best option would be to inline all `Map` subschemas when the `Option.MAP_VALUES_AS_ADDITIONAL_PROPERTIES` is enabled and thereby avoid the `$defs` entry, similarly to how all lists/arrays are always inlined. Would you deem this acceptable for your example?
```json
{
  "$schema" : "https://json-schema.org/draft/2019-09/schema",
  "$defs" : {
    "ValueSchema" : {
      "type" : "object",
      "properties" : {
        "int_value" : {
          "type" : "integer"
        },
        "string_value" : {
          "type" : "string"
        }
      }
    }
  },
  "type" : "object",
  "properties" : {
    "map_value" : {
      "type" : "object",
      "additionalProperties" : {
        "$ref" : "#/$defs/ValueSchema"
      }
    }
  }
}
```

Alternatively I suppose, for your given scenario where the `additionalProperties` are the same, the redundant field attribute could also be discarded during the "clean up" procedure at the end of the schema generation. 🤔
That probably applies for a number of different attributes, where duplication could be reduced by something like this. Sounds complicated though. 🤨

**Comment by magicDGS** [comment]
Thanks for your response, @CarstenWickner! Before my question I was already introducing the `Option.MAP_VALUES_AS_ADDITIONAL_PROPERTIES` to prevent the option, but I was wondering if the "cleaup" option that you mentioned was possible to implement within the generator (either on a custom way or contributed to the library).

In any case, from my current use case, it is enough the other option. If I need something differernt in the future I will give more thoughts to it. Thaks!

**Comment by CarstenWickner** [comment]
HI @magicDGS,

I've added a basic clean-up feature for those duplicate attributes in #428, which would cover your specific use case.
I haven't released it yet, as I'm unsure whether it's good enough as-is.

**Comment by magicDGS** [comment]
@CarstenWickner - Thanks a lot for the feedback. As soon as there is a release, I will test it on my use case. Also,  maybe this can help me to realize how can I implement a similar cleanup as I described in #425. Again, thanks for the great library and system that you are providing to the community!
