### ISSUE TITLE
How to mark fields in Class so they will be included in oneOf array ? 

### ISSUE THREAD

**Issue by kieronedwards** [victools/jsonschema-generator#437]
Hi @CarstenWickner 

I want to mark certain fields in my java class to be part of a `oneOf` array so that only one of these fields can be set in the json e.g. how do I specify the `"oneOf"` section below

```json
    "StepConfiguration": {
      "type": "object",
      "properties": {
        "description": {
          "type": "string"
        },
        "errorHandling": {
          "$ref": "#/$defs/ErrorHandlingConfiguration"
        },
        "name": {
          "type": "string"
        },
        "filter": {
          "$ref": "#/$defs/FilterComponentConfiguration"
        },
        "parallelRunComponent": {
          "$ref": "#/$defs/ParallelRunComponentConfiguration"
        },
        "payloadExpressionComponent": {
          "$ref": "#/$defs/PayloadExpressionComponentConfiguration"
        },
        "stepComponentConfiguration": {}
      },
      "required": [
        "name"
      ],
      "oneOf" : [
        {"required" :  ["filter"]},
        {"required" :  ["parallelRunComponent"]},
        {"required" :  ["payloadExpressionComponent"]}
      ],
      "additionalProperties": false
    }
```

As this seems quite a common req - is there any standard way of doing this? Or do I have to follow what you suggested here and use a custom class and my own annotation to mark the fields I want only to be part of the `oneOf` clause. 

 _Originally posted by @CarstenWickner in https://github.com/victools/jsonschema-generator/issues/319#issuecomment-1465019508_

**Comment by CarstenWickner** [comment]
Hi @kieronedwards,

Not sure how common this use-case is exactly. I could imagine it's often even more complicated, e.g., if property `a` has the value `x`, property `b` is required – otherwise properties `c` and `d` are required. Your's is a comparatively simple example, that should be easy enough to cover, yeah.

I know of no standard annotation covering your given use-case, i.e., if your answer to the question "How is this supposed to be indicated on my Java class?" is: "Via a (custom) annotation", then you may not get around creating one yourself, yes.
Based on such annotation, you could then use an approach similar to what I provided on #319, exactly.
