### ISSUE TITLE
Unable to get correct sub-type definition for generic collection

### ISSUE THREAD

**Issue by nlenoire** [victools/jsonschema-generator#439]
Hello,

I'm facing the following issue:

I have a kotlin classes defined as follow:

```
abstract class Classifier(val name: String, val attributes: List<Attribute>)
```

```
class Attribute(val name: String, val dataType: String)
```

```
class Entity(name: String, attributes: List<EntityAttribute>) : Classifier(name, attributes)
```

```
class EntityAttribute(name: String, dataType: String, val required: Boolean) : Attribute(name, dataType)
```

When I generate JSON schema for the class `Entity`, the generator define a sub-schema corresponding the class `Attribute`, but not to the class `EntityAttribute`.

Is it a known limitation?

Thanks for your help.

**Comment by CarstenWickner** [comment]
Hi @nlenoire,

You're saying the `attributes: List<Attribute>` declared on the `Classifier` are overriding the more specific `attributes: List<EntityAttribute>` of the `Entity` type?
I suspect that is due to the generated `List<Attribute> getAttributes()` method on the `Classifier` not being properly overridden as `List<EntityAttribute> getAttributes()` on the `Entity` class when you're defining it like this.

I have no experience with Kotlin and therefore can only speculate how this kind of more specific return value would be reflected in what the generator gets to work with here. Perhaps Kotlin doesn't bother overriding the getter method and from a Java perspective, the `Entity::getAttribute` method still returns `List<Attribute>`.
One would have to play around with it to see what information we have to go on here.

Others have raised questions regarding Kotlin. You might want to mention some of those people here and get their input.
I'd be happy to extend the library in any way to cover the usage under Kotlin as well. Would just need to get a better idea what is available.

**Comment by nlenoire** [comment]
Good catch !!! That was exactly the issue :)
