### ISSUE TITLE
Can you release jsonschema-module-jackson 4.7.0?

### ISSUE THREAD

**Issue by jordanjennings** [victools/jsonschema-generator#54]
Apologies for opening this issue here, but issues are not enabled for jsonschema-module-jackson.

It would be very convenient to have a unified release version for all your jsonschema components, and it looks like you are at least partially doing that for jsonschema-module-javax-validation like:

![image](https://user-images.githubusercontent.com/1031913/77457380-fb9ab000-6dd2-11ea-8d29-6a6fe87c451e.png)

Can you release a 4.7.0 Compatibility Declaration for jsonschema-module-jackson also? Thanks!

**Comment by CarstenWickner** [comment]
Hi @jordanjennings,

No apologies needed, that’s exactly why „Issues“ are only enabled here.

I guess I should combine all of the (standard) modules into a single repository with the main generator here then. Otherwise the release process is too cumbersome.
So far, I‘ve only done this „compatibility declaration“ kind of release after making breaking changes or in this case after deprecating some things.

So far, I hadn’t done it for the jackson module because I am still working on new features for `v4.7.0`.

I‘ll combine all this into one multi-module project. Just don’t know when I’ll get to it exactly.
Will keep you posted.

**Comment by CarstenWickner** [comment]
HI @jordanjennings,

as short-term solution I've done the release of the jackson module [v4.7.0](https://github.com/victools/jsonschema-module-jackson/releases/tag/v4.7.0) now.
My pending changes will simply have to go into v4.8.0 then. 😉

I'll keep this issue here open until I've merged the separate repositories into the main one to ensure that future releases always include all (standard) modules.

**Comment by jordanjennings** [comment]
Awesome, thanks for the quick resolution!

**Comment by JanLabrie** [comment]
Carsten,

Just to be sure: This does mean that you will not maintain the 'standalone' repositories like victools/jsonschema-module-jackson anymore right?

Cheers,

Jan

**Comment by CarstenWickner** [comment]
HI @JanLabrie,

Yes, that's my plan. On the `jsonschema-generator`'s `master` branch, it is already a maven multi-module project.
Once I've done the next release, I'll update the README files in the module repositories and set them to "Archived".

**Comment by CarstenWickner** [comment]
It is done.
- Version 4.8.0 has been released. The first release from the mono-repo.
- The "standalone" module repositories have been archived in favor of the mono-repo as well.

From now on, the release versions should all be in sync.
